{
 "title": "Telegram Bot Metrics",
 "description": "Comprehensive monitoring for Telegram bot",
 "tags": [
  "telegram",
  "bot",
  "monitoring"
 ],
 "time": { "from": "2025-07-13T19:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(tgbot_requests_total, path_template)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(tgbot_requests_total[1m])", "legendFormat": "{{method}} {{path_template}}" }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(tgbot_responses_total[1m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request Duration (99th percentile)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tgbot_request_duration_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Requests in Progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tgbot_requests_in_progress)"
    }
   ]
  },
  {
   "title": "Top Slow Endpoints",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.95, sum by(path_template) (rate(tgbot_request_duration_seconds_bucket[1m]))))"
    }
   ]
  },
  {
   "title": "Exceptions by Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(exception_type) (rate(tgbot_exceptions_total[1m]))",
     "legendFormat": "{{exception_type}}"
    }
   ]
  },
  {
   "title": "Category Clicks Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk(20, sum by(button_text) (rate(tgbot_category_clicks_total[1y]))",
     "legendFormat": "{{button_text}}"
    }
   ]
  },
  {
   "title": "Category Clicks Proportion",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(button_text) (tgbot_category_clicks_total)",
     "legendFormat": "{{button_text}}"
    }
   ]
  },
  {
   "title": "Last Activity by Category",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "tgbot_category_last_click_timestamp"
    }
   ]
  }
 ]
}