# made by donBarbos https://github.com/donBarbos/telegram-bot-template
global:
  scrape_interval: 15s # 1m
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s # 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "tgbot"
    scrape_interval: 15s
    file_sd_configs:
      - files: ['/etc/prometheus/targets.json']
    metrics_path: /metrics
    scheme: http