services:
  admin:
    build:
      context: ../skolkovo_admin/
      dockerfile: ../docker/Dockerfile.admin
    ports:
      - "8080:8080"
    # volumes:
    #   - media-data:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ../config/.env
    command: >
      sh -c "python manage.py migrate && 
      python manage.py migrate sessions && 
      gunicorn skolkovo_admin.wsgi --bind=0.0.0.0:8080"

  bot:
    container_name: bot
    build:
      dockerfile: ../docker/Dockerfile.bot
      context: ../bot
    command: python main.py
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ../config/.env

  db:
    container_name: db
    image: postgres:16.3
    ports:
      - "5432:5432"
    env_file:
      - ../config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ../config/.env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 1s
      retries: 3

volumes:
  postgres_data:
  redis-data:
