"""description ru en

Revision ID: 3b47491a2100
Revises: c7277fe299dc
Create Date: 2025-07-15 18:15:05.931206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b47491a2100'
down_revision: Union[str, Sequence[str], None] = 'c7277fe299dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('description_ru', sa.Text(), nullable=True))
    op.add_column('category', sa.Column('description_en', sa.Text(), nullable=True))
    op.drop_column('category', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('category', 'description_en')
    op.drop_column('category', 'description_ru')
    # ### end Alembic commands ###
