# Generated by Django 5.2.4 on 2025-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_telegramuser_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
