# Generated by Django 5.2.4 on 2025-07-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_title_category_title_ru_category_title_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='personal_data_agreement',
        ),
    ]
