# Generated by Django 5.2.4 on 2025-07-16 09:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_telegramuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=10),
        ),
    ]
