# Generated by Django 5.2.4 on 2025-07-16 09:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_category_images_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='images_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, help_text='Список URL изображений', null=True, size=None),
        ),
    ]
