# Generated by Django 5.2.4 on 2025-07-16 15:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_category_images_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='images_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, help_text='Список URL изображений', null=True, size=None, verbose_name='Ссылки на изображения (ЧЕРЕЗ ЗАПЯТУЮ)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main_app.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
