# Generated by Django 5.2.4 on 2025-07-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_category_images_urls_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
