# Generated by Django 5.2.4 on 2025-07-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_telegramuser_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_num',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
