# Generated by Django 5.2.4 on 2025-07-19 07:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_category_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='videos_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, help_text='Список URL видео', null=True, size=None, verbose_name='Ссылки на видео (ЧЕРЕЗ ЗАПЯТУЮ)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order_num',
            field=models.IntegerField(blank=True, verbose_name='Порядковый номер'),
        ),
    ]
