# Generated by Django 5.2.4 on 2025-07-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_question_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
