# Generated by Django 5.2.4 on 2025-07-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_question_embedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='answer_ru',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
